In [160]:
import pandas as pd
import numpy as np
from tableone import TableOne
from eda_utils import *
#show more columns
pd.set_option('display.max_columns', None)

In [161]:
#read in the data, with str for all columns
data = pd.read_csv('../data/table1_data.csv', dtype=str, index_col='Case Key')
print(data.shape)
data.head()

(53684, 48)


Facility Key Facility Type  \
Case Key                                                           
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2   WIEPJSGATB           3.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f   NWBQYGAYAV           3.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b   KOZLUMSSEP           3.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e   QISENWRSZO           3.0   
D1557dfde-4686-4534-8d7f-bf743fdc51bf   OPDMCOUQIW           4.0   

                                      Facility Location Age at Diagnosis  Sex  \
Case Key                                                                        
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2               2.0             78.0  2.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f               5.0             70.0  1.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b               2.0             82.0  1.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e               6.0             51.0  1.0   
D1557dfde-4686-4534-8d7f-bf743fdc51bf               3.0             84.0  1.0   

                                      Race Spanish Hispanic Origin  \
Case Key                                                             
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2  1.0                     9.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f  1.0                     0.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b  1.0                     0.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e  1.0                     0.0   
D1557dfde-4686-4534-8d7f-bf743fdc51bf  1.0                     0.0   

                                      Primary Payor  \
Case Key                                              
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2           3.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f           1.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b           3.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e           1.0   
D1557dfde-4686-4534-8d7f-bf743fdc51bf           3.0   

                                      Census Median Income Quartiles 2008-2012  \
Case Key                                                                         
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2                                      4.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f                                      1.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b                                      4.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e                                      NaN   
D1557dfde-4686-4534-8d7f-bf743fdc51bf                                      3.0   

                                      Percent No High School Degree 2008-2012  \
Case Key                                                                        
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2                                     4.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f                                     1.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b                                     4.0   
D67bf0834-7b7d-41c7-a320-ab0438fe764e                                     NaN   
D1557dfde-4686-4534-8d7f-bf743fdc51bf                                     4.0   

                                      Urban/Rural 2013 Great Circle Distance  \
Case Key                                                                       
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2              1.0                   7.5   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f              3.0                  26.5   
D656e0503-a772-440d-a60a-c9d8bd9c520b              1.0                   7.9   
D67bf0834-7b7d-41c7-a320-ab0438fe764e              1.0                   NaN   
D1557dfde-4686-4534-8d7f-bf743fdc51bf              3.0                   2.7   

                                      Charlson-Deyo Score Year of Diagnosis  \
Case Key                                                                      
D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2                 0.0            2010.0   
Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f                 2.0            2012.0   
D656e0503-a772-440d-a60a-c9d8bd9c520b                 0.0            2017.0   
D67bf0834-7b7d-41

In [162]:
cols = data.columns.to_list()
num_cols = ['Age at Diagnosis', 'Great Circle Distance', 'Size of Tumor', 'CEA value', 'Tumor Size Summary 2016', 'CEA Pretreatment Lab Value SSDI Item 3820']
cat_cols = [x for x in cols if x not in num_cols]

In [163]:
# 'First Surgical Procedure, Days from Dx','Definitive Surgical Procedure, Days from Dx','Radiation, Days from Dx','Radiation Ended, Days from Start of Radiation','Systemic, Days from Dx','Chemotherapy, Days from Dx','Total Dose',

In [164]:
#convert numeric columns to float
for col in num_cols:
    data[col] = data[col].astype(float)

In [165]:
facility_by_year = pd.DataFrame(pd.crosstab(data['Facility Key'], data['Year of Diagnosis'], margins=True))
facility_by_year.head()


Year of Diagnosis  2010.0  2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  \
Facility Key                                                                
ABZFZYJZCA              1       0       1       0       0       2       0   
ACOYXZPJUG              0       0       0       0       0       0       0   
ADSHBUUWZC              4       4       0       7       2       2       2   
ADXGCKXJNR              0       9      13      12      19      11       9   
ADXQMZWWTZ              1       2       2       1       0       1       2   

Year of Diagnosis  2017.0  2018.0  2019.0  All  
Facility Key                                    
ABZFZYJZCA              2       0       3    9  
ACOYXZPJUG              0       0       6    6  
ADSHBUUWZC              3       5       1   30  
ADXGCKXJNR             12       9       8  102  
ADXQMZWWTZ              0       4       2   15

In [166]:
facility_counts = pd.DataFrame(facility_by_year['All'])


In [167]:
#drop the last row, which is the total
facility_counts.drop(facility_counts.tail(1).index, inplace=True)

facility_by_year = pd.DataFrame(pd.crosstab(data['Facility Key'], data['Year of Diagnosis']))
facility_by_year['num_zero'] = -1


In [168]:
for i,row in facility_by_year.iterrows():
    try:
        row['num_zero'] = pd.DataFrame(facility_by_year.loc[i].value_counts()).loc[0][0]
    except KeyError:
        row['num_zero'] = 0
facility_by_year.head()


Year of Diagnosis  2010.0  2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  \
Facility Key                                                                
ABZFZYJZCA              1       0       1       0       0       2       0   
ACOYXZPJUG              0       0       0       0       0       0       0   
ADSHBUUWZC              4       4       0       7       2       2       2   
ADXGCKXJNR              0       9      13      12      19      11       9   
ADXQMZWWTZ              1       2       2       1       0       1       2   

Year of Diagnosis  2017.0  2018.0  2019.0  num_zero  
Facility Key                                         
ABZFZYJZCA              2       0       3         5  
ACOYXZPJUG              0       0       6         9  
ADSHBUUWZC              3       5       1         1  
ADXGCKXJNR             12       9       8         1  
ADXQMZWWTZ              0       4       2         2

In [169]:
facility_by_year['num_zero'] = 10 - facility_by_year['num_zero']
facility_by_year.head()

Year of Diagnosis  2010.0  2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  \
Facility Key                                                                
ABZFZYJZCA              1       0       1       0       0       2       0   
ACOYXZPJUG              0       0       0       0       0       0       0   
ADSHBUUWZC              4       4       0       7       2       2       2   
ADXGCKXJNR              0       9      13      12      19      11       9   
ADXQMZWWTZ              1       2       2       1       0       1       2   

Year of Diagnosis  2017.0  2018.0  2019.0  num_zero  
Facility Key                                         
ABZFZYJZCA              2       0       3         5  
ACOYXZPJUG              0       0       6         1  
ADSHBUUWZC              3       5       1         9  
ADXGCKXJNR             12       9       8         9  
ADXQMZWWTZ              0       4       2         8

In [170]:
facility_counts['num_zero'] = facility_by_year['num_zero']
facility_counts.head()


All  num_zero
Facility Key               
ABZFZYJZCA      9         5
ACOYXZPJUG      6         1
ADSHBUUWZC     30         9
ADXGCKXJNR    102         9
ADXQMZWWTZ     15         8

In [171]:
facility_counts['norm'] = facility_counts['All'] / facility_counts['num_zero']
facility_counts.head()


All  num_zero       norm
Facility Key                          
ABZFZYJZCA      9         5   1.800000
ACOYXZPJUG      6         1   6.000000
ADSHBUUWZC     30         9   3.333333
ADXGCKXJNR    102         9  11.333333
ADXQMZWWTZ     15         8   1.875000

In [172]:
facility_counts['norm'].describe()


count    1300.000000
mean        4.635846
std         4.837016
min         1.000000
25%         1.833333
50%         3.000000
75%         5.444444
max        55.000000
Name: norm, dtype: float64

In [173]:
facility_counts.sort_values(by='norm', ascending=False, inplace=True)
len(facility_counts)


1300

In [174]:
fac_ids = facility_counts.index.to_list()
facs1 = fac_ids[0:329]
facs2 = fac_ids[330:659]
facs3 = fac_ids[660:989]
facs4 = fac_ids[990:1315]

data['facs_quart'] = np.NaN
data.loc[data['Facility Key'].isin(facs1), 'facs_quart'] = 1
data.loc[data['Facility Key'].isin(facs2), 'facs_quart'] = 2
data.loc[data['Facility Key'].isin(facs3), 'facs_quart'] = 3
data.loc[data['Facility Key'].isin(facs4), 'facs_quart'] = 4

data.drop('Facility Key', axis=1, inplace=True)

data['facs_quart'].value_counts(dropna=False)

1.0    34539
2.0    11496
3.0     5406
4.0     2147
NaN       96
Name: facs_quart, dtype: int64

In [175]:
data.rename(columns={'facs_quart': 'Facility Volume, Quartile'}, inplace=True)

In [176]:
data['Facility Type'].value_counts(dropna=False)

2.0    19114
3.0    18052
4.0    10786
1.0     3045
NaN     2687
Name: Facility Type, dtype: int64

In [177]:
data.loc[data['Facility Type'] == '1.0', 'Facility Type'] = 'Community Cancer Program'
data.loc[data['Facility Type'] == '2.0', 'Facility Type'] = 'Comprehensive Community Cancer Program'
data.loc[data['Facility Type'] == '3.0', 'Facility Type'] = 'Academic/Research Program'
data.loc[data['Facility Type'] == '4.0', 'Facility Type'] = 'Integrated Network Cancer Program'

data.loc[data['Facility Type'] == 'nan', 'Facility Type'] = 'Unknown'
data.loc[data['Facility Type'] == 'None assigned', 'Facility Type'] = np.NaN
data['Facility Type'].fillna('Unknown', inplace=True)
data.loc[data['Facility Type'] == "Unknown", 'Facility Type'] = np.NaN
data['Facility Type'].value_counts(dropna=False)

Comprehensive Community Cancer Program    19114
Academic/Research Program                 18052
Integrated Network Cancer Program         10786
Community Cancer Program                   3045
NaN                                        2687
Name: Facility Type, dtype: int64

In [178]:
data['Facility Location'].value_counts()

3.0    9990
4.0    9927
2.0    6792
9.0    6282
6.0    5175
7.0    4226
5.0    3337
1.0    2822
8.0    2446
Name: Facility Location, dtype: int64

In [179]:
data.loc[data['Facility Location'] == '1.0', 'Facility Location'] = 'NE'
data.loc[data['Facility Location'] == '2.0', 'Facility Location'] = 'NE'
data.loc[data['Facility Location'] == '3.0', 'Facility Location'] = 'South'
data.loc[data['Facility Location'] == '4.0', 'Facility Location'] = 'Midwest'
data.loc[data['Facility Location'] == '5.0', 'Facility Location'] = 'Midwest'
data.loc[data['Facility Location'] == '6.0', 'Facility Location'] = 'Midwest'
data.loc[data['Facility Location'] == '7.0', 'Facility Location'] = 'South'
data.loc[data['Facility Location'] == '8.0', 'Facility Location'] = 'West'
data.loc[data['Facility Location'] == '9.0', 'Facility Location'] = 'West'


In [180]:
data.loc[data['Facility Location'] == 'None assigned', 'Facility Location'] = np.NaN
data['Facility Location'].fillna('Unknown', inplace=True)
data.loc[data['Facility Location'] == "Unknown", 'Facility Location'] = np.NaN
data['Facility Location'].value_counts(dropna=False)

Midwest    18439
South      14216
NE          9614
West        8728
NaN         2687
Name: Facility Location, dtype: int64

In [181]:
data['Sex'].value_counts()


1.0    33383
2.0    20301
Name: Sex, dtype: int64

In [182]:
data.loc[data['Sex'] == '1.0', 'Sex'] = 'Male'
data.loc[data['Sex'] == '2.0', 'Sex'] = 'Female'
data.loc[data['Sex'] == 'None assigned', 'Sex'] = np.NaN
data['Sex'].fillna('Unknown', inplace=True)
data.loc[data['Sex'] == "Unknown", 'Sex'] = np.NaN
data['Sex'].value_counts(dropna=False)

Male      33383
Female    20301
Name: Sex, dtype: int64

In [183]:
data['Race'].value_counts()

1.0     45899
2.0      4269
98.0      610
96.0      559
4.0       326
3.0       308
6.0       291
10.0      197
8.0       177
15.0      160
5.0       146
16.0      137
7.0        70
97.0       35
13.0       34
11.0       28
17.0       27
27.0       20
14.0       18
12.0       15
22.0        6
20.0        5
31.0        3
25.0        2
28.0        2
32.0        1
30.0        1
Name: Race, dtype: int64

#Specific labels from the PUF Data Dictionary

data.loc[data['Race'] == '1.0', 'Race'] = 'White'

data.loc[data['Race'] == '2.0', 'Race'] = 'Black'

data.loc[data['Race'] == '3.0', 'Race'] = 'American Indian, Aleutian, or Eskimo'

data.loc[data['Race'] == '4.0', 'Race'] = 'Chinese'
data.loc[data['Race'] == '5.0', 'Race'] = 'Japanese'
data.loc[data['Race'] == '8.0', 'Race'] = 'Korean'

data.loc[data['Race'] == '6.0', 'Race'] = 'Filipino'
data.loc[data['Race'] == '7.0', 'Race'] = 'Hawaiian'
data.loc[data['Race'] == '20.0', 'Race'] = 'Micronesian, NOS'
data.loc[data['Race'] == '22.0', 'Race'] = 'Guamanian, NOS'
data.loc[data['Race'] == '27.0', 'Race'] = 'Samoan'
data.loc[data['Race'] == '28.0', 'Race'] = 'Tongan'
data.loc[data['Race'] == '31.0', 'Race'] = 'Fiji Islander'
data.loc[data['Race'] == '32.0', 'Race'] = 'New Guinean'
data.loc[data['Race'] == '97.0', 'Race'] = 'Pacific Islander, NOS'

data.loc[data['Race'] == '10.0', 'Race'] = 'Vietnamese'
data.loc[data['Race'] == '11.0', 'Race'] = 'Laotian'
data.loc[data['Race'] == '12.0', 'Race'] = 'Hmong'
data.loc[data['Race'] == '13.0', 'Race'] = 'Kampuchean (including Khmer and Cambodian)'
data.loc[data['Race'] == '14.0', 'Race'] = 'Thai'
data.loc[data['Race'] == '30.0', 'Race'] = 'Melanesian, NOS'

data.loc[data['Race'] == '15.0', 'Race'] = 'Asian Indian or Pakistani, NOS (formerly code 09)'
data.loc[data['Race'] == '16.0', 'Race'] = 'Asian Indian'
data.loc[data['Race'] == '17.0', 'Race'] = 'Pakistani'

data.loc[data['Race'] == '96.0', 'Race'] = 'Other Asian, including Asian, NOS andOriental, NOS'
data.loc[data['Race'] == '98.0', 'Race'] = 'Other'

In [184]:
data.loc[data['Race'] == '1.0', 'Race'] = 'White'

data.loc[data['Race'] == '2.0', 'Race'] = 'Black'

data.loc[data['Race'] == '3.0', 'Race'] = 'Asian'

data.loc[data['Race'] == '4.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '5.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '8.0', 'Race'] = 'Asian'

data.loc[data['Race'] == '6.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '7.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '20.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '22.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '25.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '27.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '28.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '31.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '32.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '97.0', 'Race'] = 'Asian'

data.loc[data['Race'] == '10.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '11.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '12.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '13.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '14.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '30.0', 'Race'] = 'Asian'

data.loc[data['Race'] == '15.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '16.0', 'Race'] = 'Asian'
data.loc[data['Race'] == '17.0', 'Race'] = 'Asian'

data.loc[data['Race'] == '96.0', 'Race'] = 'Other'
data.loc[data['Race'] == '98.0', 'Race'] = 'Other'


data.loc[data['Race'] == 'None assigned', 'Race'] = np.NaN
data['Race'].fillna('Unknown', inplace=True)
data.loc[data['Race'] == "Unknown", 'Race'] = np.NaN
data['Race'].value_counts(dropna=False)

White    45899
Black     4269
Asian     2009
Other     1169
NaN        338
Name: Race, dtype: int64

In [185]:
data['Spanish Hispanic Origin'].value_counts()

0.0    48773
6.0     2476
9.0     1138
1.0      649
4.0      216
2.0      152
7.0       95
5.0       68
3.0       64
8.0       53
Name: Spanish Hispanic Origin, dtype: int64

In [186]:
data.loc[data['Spanish Hispanic Origin'] == '0.0', 'Spanish Hispanic Origin'] = 'Non-Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '1.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '2.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '3.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '4.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '5.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '6.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '7.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '8.0', 'Spanish Hispanic Origin'] = 'Hispanic'
data.loc[data['Spanish Hispanic Origin'] == '9.0', 'Spanish Hispanic Origin'] = 'Unknown'

data.loc[data['Spanish Hispanic Origin'] == 'None assigned', 'Spanish Hispanic Origin'] = np.NaN
data['Spanish Hispanic Origin'].fillna('Unknown', inplace=True)
data.loc[data['Spanish Hispanic Origin'] == "Unknown", 'Spanish Hispanic Origin'] = np.NaN
data['Spanish Hispanic Origin'].value_counts(dropna=False)

Non-Hispanic    48773
Hispanic         3773
NaN              1138
Name: Spanish Hispanic Origin, dtype: int64

In [187]:
data['Primary Payor'].value_counts()

1.0    27242
3.0    18112
2.0     4688
0.0     2193
4.0      846
9.0      603
Name: Primary Payor, dtype: int64

In [188]:
data.loc[data['Primary Payor'] == '0.0', 'Primary Payor'] = 'Not Insured'
data.loc[data['Primary Payor'] == '1.0', 'Primary Payor'] = 'Private Insurance or Managed Care'
data.loc[data['Primary Payor'] == '2.0', 'Primary Payor'] = 'Medicaid'
data.loc[data['Primary Payor'] == '3.0', 'Primary Payor'] = 'Medicare/Public'
data.loc[data['Primary Payor'] == '4.0', 'Primary Payor'] = 'Medicare/Public'
data.loc[data['Primary Payor'] == '9.0', 'Primary Payor'] = 'Unknown'

data.loc[data['Primary Payor'] == 'None assigned', 'Primary Payor'] = np.NaN
data['Primary Payor'].fillna('Unknown', inplace=True)
data.loc[data['Primary Payor'] == "Unknown", 'Primary Payor'] = np.NaN
data['Primary Payor'].value_counts(dropna=False)

Private Insurance or Managed Care    27242
Medicare/Public                      18958
Medicaid                              4688
Not Insured                           2193
NaN                                    603
Name: Primary Payor, dtype: int64

In [189]:
data['Median Income Quartiles 2012-2016'].value_counts()


4.0    16295
3.0    11061
2.0    10625
1.0     8311
Name: Median Income Quartiles 2012-2016, dtype: int64

In [190]:

data.loc[data['Median Income Quartiles 2012-2016'] == '1.0', 'Median Income Quartiles 2012-2016'] = '< $40,227'
data.loc[data['Median Income Quartiles 2012-2016'] == '2.0', 'Median Income Quartiles 2012-2016'] = '$40,227 - $50,353'
data.loc[data['Median Income Quartiles 2012-2016'] == '3.0', 'Median Income Quartiles 2012-2016'] = '$50,354 - $63,332'
data.loc[data['Median Income Quartiles 2012-2016'] == '4.0', 'Median Income Quartiles 2012-2016'] = '>=$63,333'

data.loc[data['Median Income Quartiles 2012-2016'] == 'nan', 'Median Income Quartiles 2012-2016'] = np.NaN
data.loc[data['Median Income Quartiles 2012-2016'] == 'None assigned', 'Median Income Quartiles 2012-2016'] = np.NaN
data['Median Income Quartiles 2012-2016'].fillna('Unknown', inplace=True)
data.loc[data['Median Income Quartiles 2012-2016'] == "Unknown", 'Median Income Quartiles 2012-2016'] = np.NaN
data['Median Income Quartiles 2012-2016'].value_counts(dropna=False)

>=$63,333            16295
$50,354 - $63,332    11061
$40,227 - $50,353    10625
< $40,227             8311
NaN                   7392
Name: Median Income Quartiles 2012-2016, dtype: int64

In [191]:
data['Census Median Income Quartiles 2008-2012'].value_counts()

4.0    14889
3.0    12729
2.0    11310
1.0     7821
Name: Census Median Income Quartiles 2008-2012, dtype: int64

In [192]:
data.loc[data['Census Median Income Quartiles 2008-2012'] == '1.0', 'Census Median Income Quartiles 2008-2012'] = '< $40,227'
data.loc[data['Census Median Income Quartiles 2008-2012'] == '2.0', 'Census Median Income Quartiles 2008-2012'] = '$40,227 - $50,353'
data.loc[data['Census Median Income Quartiles 2008-2012'] == '3.0', 'Census Median Income Quartiles 2008-2012'] = '$50,354 - $63,332'
data.loc[data['Census Median Income Quartiles 2008-2012'] == '4.0', 'Census Median Income Quartiles 2008-2012'] = '>=$63,333'

data.loc[data['Census Median Income Quartiles 2008-2012'] == 'None assigned', 'Census Median Income Quartiles 2008-2012'] = np.NaN
data['Census Median Income Quartiles 2008-2012'].fillna('Unknown', inplace=True)
data.loc[data['Census Median Income Quartiles 2008-2012'] == "Unknown", 'Census Median Income Quartiles 2008-2012'] = np.NaN
data['Census Median Income Quartiles 2008-2012'].value_counts(dropna=False)

>=$63,333            14889
$50,354 - $63,332    12729
$40,227 - $50,353    11310
< $40,227             7821
NaN                   6935
Name: Census Median Income Quartiles 2008-2012, dtype: int64

In [193]:
#if 'Mean Income Quartiles 2012-2016' is missing, fill with 'Census Median Income Quartiles 2008-2012'
data.loc[data['Median Income Quartiles 2012-2016'].isnull(), 'Median Income Quartiles 2012-2016'] = data.loc[data['Median Income Quartiles 2012-2016'].isnull(), 'Census Median Income Quartiles 2008-2012']
data['Median Income Quartiles 2012-2016'].value_counts()

>=$63,333            16394
$50,354 - $63,332    11170
$40,227 - $50,353    10748
< $40,227             8439
Name: Median Income Quartiles 2012-2016, dtype: int64

In [194]:
data.rename({'Median Income Quartiles 2012-2016':'Median Income Quartile'}, inplace=True)
data.drop(['Census Median Income Quartiles 2008-2012'], axis=1, inplace=True)

In [195]:
data['Percent No High School Degree 2008-2012'].value_counts()

3.0    15268
2.0    12224
4.0    11168
1.0     8110
Name: Percent No High School Degree 2008-2012, dtype: int64

In [196]:
data.loc[data['Percent No High School Degree 2008-2012'] == '1.0', 'Percent No High School Degree 2008-2012'] = '>=17.6%'
data.loc[data['Percent No High School Degree 2008-2012'] == '2.0', 'Percent No High School Degree 2008-2012'] = '10.9 - 17.5%'
data.loc[data['Percent No High School Degree 2008-2012'] == '3.0', 'Percent No High School Degree 2008-2012'] = '6.3 - 10.8%'
data.loc[data['Percent No High School Degree 2008-2012'] == '4.0', 'Percent No High School Degree 2008-2012'] =  '< 6.3%'

data.loc[data['Percent No High School Degree 2008-2012'] == 'None assigned', 'Percent No High School Degree 2008-2012'] = np.NaN
data['Percent No High School Degree 2008-2012'].fillna('Unknown', inplace=True)
data.loc[data['Percent No High School Degree 2008-2012'] == "Unknown", 'Percent No High School Degree 2008-2012'] = np.NaN
data['Percent No High School Degree 2008-2012'].value_counts(dropna=False)

6.3 - 10.8%     15268
10.9 - 17.5%    12224
< 6.3%          11168
>=17.6%          8110
NaN              6914
Name: Percent No High School Degree 2008-2012, dtype: int64

In [197]:
data['Percent No High School Degree Quartiles 2012-2016'].value_counts()


3.0    13104
2.0    12219
4.0    11309
1.0     9729
Name: Percent No High School Degree Quartiles 2012-2016, dtype: int64

In [198]:
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == '1.0', 'Percent No High School Degree Quartiles 2012-2016'] = '>=17.6%'
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == '2.0', 'Percent No High School Degree Quartiles 2012-2016'] = '10.9 - 17.5%'
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == '3.0', 'Percent No High School Degree Quartiles 2012-2016'] = '6.3 - 10.8%'
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == '4.0', 'Percent No High School Degree Quartiles 2012-2016'] = '< 6.3%'

data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == 'nan', 'Percent No High School Degree Quartiles 2012-2016'] = np.NaN
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == 'None assigned', 'Percent No High School Degree Quartiles 2012-2016'] = np.NaN
data['Percent No High School Degree Quartiles 2012-2016'].fillna('Unknown', inplace=True)
data.loc[data['Percent No High School Degree Quartiles 2012-2016'] == "Unknown", 'Percent No High School Degree Quartiles 2012-2016'] = np.NaN
data['Percent No High School Degree Quartiles 2012-2016'].value_counts(dropna=False)

6.3 - 10.8%     13104
10.9 - 17.5%    12219
< 6.3%          11309
>=17.6%          9729
NaN              7323
Name: Percent No High School Degree Quartiles 2012-2016, dtype: int64

In [199]:
data.loc[data['Percent No High School Degree Quartiles 2012-2016'].isnull(), 'Percent No High School Degree Quartiles 2012-2016'] = data.loc[data['Percent No High School Degree Quartiles 2012-2016'].isnull(), 'Percent No High School Degree 2008-2012']


In [200]:
data['Percent No High School Degree Quartiles 2012-2016'].value_counts(dropna=False)

6.3 - 10.8%     13223
10.9 - 17.5%    12340
< 6.3%          11384
>=17.6%          9825
NaN              6912
Name: Percent No High School Degree Quartiles 2012-2016, dtype: int64

In [201]:
data.rename({'Percent No High School Degree Quartiles 2012-2016':'Percent No High School Degree Quartile'}, inplace=True)
data.drop(['Percent No High School Degree 2008-2012'], axis=1, inplace=True)

In [202]:
data['Urban/Rural 2013'].value_counts()

1.0    26122
2.0    11029
3.0     5108
6.0     3251
4.0     2771
7.0     1639
5.0      785
9.0      637
8.0      570
Name: Urban/Rural 2013, dtype: int64

In [203]:
data.loc[data['Urban/Rural 2013'] == '1.0', 'Urban/Rural 2013'] = 'Urban'
data.loc[data['Urban/Rural 2013'] == '2.0', 'Urban/Rural 2013'] = 'Urban'
data.loc[data['Urban/Rural 2013'] == '3.0', 'Urban/Rural 2013'] = 'Urban'
data.loc[data['Urban/Rural 2013'] == '4.0', 'Urban/Rural 2013'] = 'Suburban'
data.loc[data['Urban/Rural 2013'] == '5.0', 'Urban/Rural 2013'] = 'Suburban'
data.loc[data['Urban/Rural 2013'] == '6.0', 'Urban/Rural 2013'] = 'Suburban'
data.loc[data['Urban/Rural 2013'] == '7.0', 'Urban/Rural 2013'] = 'Rural'
data.loc[data['Urban/Rural 2013'] == '8.0', 'Urban/Rural 2013'] = 'Rural'
data.loc[data['Urban/Rural 2013'] == '9.0', 'Urban/Rural 2013'] = 'Rural'

data.loc[data['Urban/Rural 2013'] == 'None assigned', 'Urban/Rural 2013'] = np.NaN
data['Urban/Rural 2013'].fillna('Unknown', inplace=True)
data.loc[data['Urban/Rural 2013'] == "Unknown", 'Urban/Rural 2013'] = np.NaN
data['Urban/Rural 2013'].value_counts(dropna=False)

Urban       42259
Suburban     6807
Rural        2846
NaN          1772
Name: Urban/Rural 2013, dtype: int64

In [204]:
data['Charlson-Deyo Score'].value_counts()


0.0    42115
1.0     8528
2.0     1977
3.0     1064
Name: Charlson-Deyo Score, dtype: int64

In [205]:
data.loc[data['Charlson-Deyo Score'] == '0.0', 'Charlson-Deyo Score'] = 'Score of 0'
data.loc[data['Charlson-Deyo Score'] == '1.0', 'Charlson-Deyo Score'] = 'Score of 1'
data.loc[data['Charlson-Deyo Score'] == '2.0', 'Charlson-Deyo Score'] = 'Score of 2 or more'
data.loc[data['Charlson-Deyo Score'] == '3.0', 'Charlson-Deyo Score'] = 'Score of 2 or more'


data.loc[data['Charlson-Deyo Score'] == 'None assigned', 'Charlson-Deyo Score'] = np.NaN
data['Charlson-Deyo Score'].fillna('Unknown', inplace=True)
data.loc[data['Charlson-Deyo Score'] == "Unknown", 'Charlson-Deyo Score'] = np.NaN
data['Charlson-Deyo Score'].value_counts(dropna=False)

Score of 0            42115
Score of 1             8528
Score of 2 or more     3041
Name: Charlson-Deyo Score, dtype: int64

In [206]:
data['Histology'].value_counts()

8140.0    46181
8480.0     2151
8263.0     1909
8210.0     1741
8261.0      478
8490.0      316
8010.0      222
8255.0      124
8481.0      118
8070.0      115
8000.0       82
8246.0       41
8560.0       33
8574.0       20
8244.0       18
8144.0       12
8211.0       12
8510.0       11
8083.0        9
8041.0        9
8013.0        9
8262.0        8
8240.0        8
8071.0        6
8072.0        6
8220.0        5
8936.0        3
8310.0        3
8249.0        3
8033.0        2
8020.0        2
8260.0        2
8245.0        2
8323.0        2
8120.0        2
8507.0        2
8221.0        2
8570.0        2
8482.0        1
8074.0        1
8571.0        1
8576.0        1
8084.0        1
8500.0        1
8542.0        1
8265.0        1
8213.0        1
8124.0        1
8046.0        1
8123.0        1
8230.0        1
Name: Histology, dtype: int64

In [207]:
data.loc[data['Histology'] == '8000.0', 'Histology'] = 'Neoplasm, benign'
data.loc[data['Histology'] == '8010.0', 'Histology'] = 'Epithelial tumor, benign'
data.loc[data['Histology'] == '8012.0', 'Histology'] = 'Large cell carcinoma, NOS'
data.loc[data['Histology'] == '8013.0', 'Histology'] = 'Large cell neuroendocrine carcinoma'
data.loc[data['Histology'] == '8014.0', 'Histology'] = 'Large cell carcinoma with rhabdoid phenotype'
data.loc[data['Histology'] == '8020.0', 'Histology'] = 'Dedifferentiated carcinoma'
data.loc[data['Histology'] == '8021.0', 'Histology'] = 'Carcinoma, anaplastic, NOS'
data.loc[data['Histology'] == '8022.0', 'Histology'] = 'Pleomorphic carcinoma'
data.loc[data['Histology'] == '8033.0', 'Histology'] = 'Pseudosarcomatous carcinoma'
data.loc[data['Histology'] == '8041.0', 'Histology'] = 'Small cell carcinoma, NOS'
data.loc[data['Histology'] == '8046.0', 'Histology'] = 'Non-small cell carcinoma'
data.loc[data['Histology'] == '8070.0', 'Histology'] = 'Actinic keratosis'
data.loc[data['Histology'] == '8071.0', 'Histology'] = 'Differentiated intraepithelial neoplasia'
data.loc[data['Histology'] == '8072.0', 'Histology'] = 'Large cell acanthoma'
data.loc[data['Histology'] == '8074.0', 'Histology'] = 'Squamous cell carcinoma, spindle cell'
data.loc[data['Histology'] == '8083.0', 'Histology'] = 'Basaloid squamous cell carcinoma'
data.loc[data['Histology'] == '8084.0', 'Histology'] = 'Clear cell acanthoma'
data.loc[data['Histology'] == '8120.0', 'Histology'] = 'Urothelial papilloma, NOS'
data.loc[data['Histology'] == '8123.0', 'Histology'] = 'Basaloid carcinoma'
data.loc[data['Histology'] == '8124.0', 'Histology'] = 'Cloacogenic carcinoma'
data.loc[data['Histology'] == '8140.0', 'Histology'] = 'Adenoma, NOS'
data.loc[data['Histology'] == '8144.0', 'Histology'] = 'Adenoma, intestinal type'
data.loc[data['Histology'] == '8201.0', 'Histology'] = 'Cribriform carcinoma in situ'
data.loc[data['Histology'] == '8210.0', 'Histology'] = 'Adenomatous polyp, NOS'
data.loc[data['Histology'] == '8211.0', 'Histology'] = 'Tubular adenoma, NOS'
data.loc[data['Histology'] == '8213.0', 'Histology'] = 'Serrated adenoma, NOS'
data.loc[data['Histology'] == '8220.0', 'Histology'] = 'Adenomatous polyposis coli'
data.loc[data['Histology'] == '8221.0', 'Histology'] = 'Multiple adenomatous polyps'
data.loc[data['Histology'] == '8230.0', 'Histology'] = 'Ductal carcinoma in situ, solid type'
data.loc[data['Histology'] == '8240.0', 'Histology'] = 'Neuroendocrine tumor, NOS'
data.loc[data['Histology'] == '8243.0', 'Histology'] = 'Goblet cell carcinoid'
data.loc[data['Histology'] == '8244.0', 'Histology'] = 'Mixed adenoneuroendocrine carcinoma'
data.loc[data['Histology'] == '8245.0', 'Histology'] = 'Tubular carcinoid'
data.loc[data['Histology'] == '8246.0', 'Histology'] = 'Neuroendocrine carcinoma, NOS'
data.loc[data['Histology'] == '8249.0', 'Histology'] = 'Neuroendocrine tumor, grade 2'
data.loc[data['Histology'] == '8255.0', 'Histology'] = 'Adenocarcinoma with mixed subtypes'
data.loc[data['Histology'] == '8260.0', 'Histology'] = 'Papillary adenoma, NOS'
data.loc[data['Histology'] == '8261.0', 'Histology'] = 'Villous adenoma, NOS'
data.loc[data['Histology'] == '8262.0', 'Histology'] = 'Villous adenocarcinoma'
data.loc[data['Histology'] == '8263.0', 'Histology'] = 'Tubulovillous adenoma, NOS'
data.loc[data['Histology'] == '8310.0', 'Histology'] = 'Clear cell adenoma'
data.loc[data['Histology'] == '8323.0', 'Histology'] = 'Mixed cell adenoma'
data.loc[data['Histology'] == '8401.0', 'Histology'] = 'Apocrine adenoma'
data.loc[data['Histology'] == '8410.0', 'Histology'] = 'Sebaceoma'
data.loc[data['Histology'] == '8470.0', 'Histology'] = 'Mucinous cystadenoma, NOS'
data.loc[data['Histology'] == '8480.0', 'Histology'] = 'Mucinous adenoma'
data.loc[data['Histology'] == '8481.0', 'Histology'] = 'Mucin-producing adenocarcinoma'
data.loc[data['Histology'] == '8482.0', 'Histology'] = 'Mucinous carcinoma, gastric type'
data.loc[data['Histology'] == '8490.0', 'Histology'] = 'Signet ring cell carcinoma'
data.loc[data['Histology'] == '8507.0', 'Histology'] = 'Intraductal micropapillary carcinoma'
data.loc[data['Histology'] == '8510.0', 'Histology'] = 'Medullary carcinoma, NOS'
data.loc[data['Histology'] == '8542.0', 'Histology'] = 'Paget disease, extramammary'
data.loc[data['Histology'] == '8560.0', 'Histology'] = 'Mixed squamous cell and glandular papilloma'
data.loc[data['Histology'] == '8570.0', 'Histology'] = 'Adenocarcinoma with squamous metaplasia'
data.loc[data['Histology'] == '8571.0', 'Histology'] = 'Adenocarcinoma with cartilaginous and osseous metaplasia'
data.loc[data['Histology'] == '8574.0', 'Histology'] = 'Adenocarcinoma with neuroendocrine differentiation'
data.loc[data['Histology'] == '8576.0', 'Histology'] = 'Hepatoid adenocarcinoma'
data.loc[data['Histology'] == '8936.0', 'Histology'] = 'Gastrointestinal stromal tumor'


data.loc[data['Histology'] == 'None assigned.0', 'Histology'] = np.NaN
data['Histology'].fillna('Unknown', inplace=True)
data.loc[data['Histology'] == "Unknown.0", 'Histology'] = np.NaN
data['Histology'].value_counts(dropna=False)

Adenoma, NOS                                                46181
Mucinous adenoma                                             2151
Tubulovillous adenoma, NOS                                   1909
Adenomatous polyp, NOS                                       1741
Villous adenoma, NOS                                          478
Signet ring cell carcinoma                                    316
Epithelial tumor, benign                                      222
Adenocarcinoma with mixed subtypes                            124
Mucin-producing adenocarcinoma                                118
Actinic keratosis                                             115
Neoplasm, benign                                               82
Neuroendocrine carcinoma, NOS                                  41
Mixed squamous cell and glandular papilloma                    33
Adenocarcinoma with neuroendocrine differentiation             20
Mixed adenoneuroendocrine carcinoma                            18
Adenoma, i

In [208]:
data['Histology'].value_counts(dropna=False)

Adenoma, NOS                                                46181
Mucinous adenoma                                             2151
Tubulovillous adenoma, NOS                                   1909
Adenomatous polyp, NOS                                       1741
Villous adenoma, NOS                                          478
Signet ring cell carcinoma                                    316
Epithelial tumor, benign                                      222
Adenocarcinoma with mixed subtypes                            124
Mucin-producing adenocarcinoma                                118
Actinic keratosis                                             115
Neoplasm, benign                                               82
Neuroendocrine carcinoma, NOS                                  41
Mixed squamous cell and glandular papilloma                    33
Adenocarcinoma with neuroendocrine differentiation             20
Mixed adenoneuroendocrine carcinoma                            18
Adenoma, i

In [209]:
data['Mucinous'] = np.NaN
data.loc[data['Histology'].str.contains('mucin', case=False, na=False), 'Mucinous'] = 1
data.loc[data['Mucinous'] !=1 , 'Mucinous'] = 0
data['Mucinous'].value_counts(dropna=False)

0.0    51414
1.0     2270
Name: Mucinous, dtype: int64

In [210]:
data['Villous'] = np.NaN
data.loc[data['Histology'].str.contains('villous', case=False, na=False), 'Villous'] = 1
data.loc[data['Villous'] !=1 , 'Villous'] = 0
data['Villous'].value_counts(dropna=False)

0.0    51289
1.0     2395
Name: Villous, dtype: int64

In [211]:
data['Signet Ring'] = np.NaN
data.loc[data['Histology'].str.contains('signet', case=False, na=False), 'Signet Ring'] = 1
data.loc[data['Signet Ring'] !=1 , 'Signet Ring'] = 0
data['Signet Ring'].value_counts(dropna=False)

0.0    53368
1.0      316
Name: Signet Ring, dtype: int64

In [212]:
data.drop('Histology', axis=1, inplace=True)

In [213]:
data['Grade 2004-2017'].value_counts()

2.0    27869
9.0     6631
3.0     3771
1.0     3011
4.0      445
Name: Grade 2004-2017, dtype: int64

In [214]:
data.loc[data['Grade 2004-2017'] == '1.0', 'Grade 2004-2017'] = 'Grade I'
data.loc[data['Grade 2004-2017'] == '2.0', 'Grade 2004-2017'] = 'Grade II'
data.loc[data['Grade 2004-2017'] == '3.0', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade 2004-2017'] == '4.0', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade 2004-2017'] == '9.0', 'Grade 2004-2017'] = np.NaN

data.loc[data['Grade 2004-2017'] == 'nan', 'Grade 2004-2017'] = np.NaN
data.loc[data['Grade 2004-2017'] == 'None assigned', 'Grade 2004-2017'] = np.NaN
data['Grade 2004-2017'].fillna('Unknown', inplace=True)
data.loc[data['Grade 2004-2017'] == "Unknown", 'Grade 2004-2017'] = np.NaN
data['Grade 2004-2017'].value_counts(dropna=False)

Grade II        27869
NaN             18588
Grade III-IV     4216
Grade I          3011
Name: Grade 2004-2017, dtype: int64

In [215]:
data['Grade Clinical SSDI Item 3843'].value_counts()

2      6761
9      3324
1       793
3       708
2.0     230
9.0      96
1.0      23
3.0      16
4         7
Name: Grade Clinical SSDI Item 3843, dtype: int64

In [216]:
data.loc[data['Grade Clinical SSDI Item 3843'] == '1.0', 'Grade 2004-2017'] = 'Grade I'
data.loc[data['Grade Clinical SSDI Item 3843'] == '2.0', 'Grade 2004-2017'] = 'Grade II'
data.loc[data['Grade Clinical SSDI Item 3843'] == '3.0', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade Clinical SSDI Item 3843'] == '4.0', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade Clinical SSDI Item 3843'] == '9.0', 'Grade 2004-2017'] = np.NaN
data.loc[data['Grade Clinical SSDI Item 3843'] == '1', 'Grade 2004-2017'] = 'Grade I'
data.loc[data['Grade Clinical SSDI Item 3843'] == '2', 'Grade 2004-2017'] = 'Grade II'
data.loc[data['Grade Clinical SSDI Item 3843'] == '3', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade Clinical SSDI Item 3843'] == '4', 'Grade 2004-2017'] = 'Grade III-IV'
data.loc[data['Grade Clinical SSDI Item 3843'] == '9', 'Grade 2004-2017'] = np.NaN
data['Grade 2004-2017'].value_counts(dropna=False)

Grade II        34860
NaN             10050
Grade III-IV     4947
Grade I          3827
Name: Grade 2004-2017, dtype: int64

In [217]:
data.drop(['Grade Clinical SSDI Item 3843'], axis=1, inplace=True)
data.rename(columns={'Grade 2004-2017': 'Grade'}, inplace=True)

In [218]:
# data['Surgical Diagnostic and Staging Procedure'].value_counts()

In [219]:
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '0.0', 'Surgical Diagnostic and Staging Procedure'] = 'Other'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '1.0', 'Surgical Diagnostic and Staging Procedure'] = 'Endoscopic biopsy'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '2.0', 'Surgical Diagnostic and Staging Procedure'] = 'Endoscopic biopsy'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '3.0', 'Surgical Diagnostic and Staging Procedure'] = 'Other'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '4.0', 'Surgical Diagnostic and Staging Procedure'] = 'Other'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '5.0', 'Surgical Diagnostic and Staging Procedure'] = 'Operative biopsy'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '6.0', 'Surgical Diagnostic and Staging Procedure'] = 'Operative biopsy'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '7.0', 'Surgical Diagnostic and Staging Procedure'] = 'Operative biopsy'
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == '9.0', 'Surgical Diagnostic and Staging Procedure'] = 'Other'


# data.loc[data['Surgical Diagnostic and Staging Procedure'] == 'None assigned', 'Surgical Diagnostic and Staging Procedure'] = np.NaN
# data['Surgical Diagnostic and Staging Procedure'].fillna('Unknown', inplace=True)
# data.loc[data['Surgical Diagnostic and Staging Procedure'] == "Unknown", 'Surgical Diagnostic and Staging Procedure'] = np.NaN
# data['Surgical Diagnostic and Staging Procedure'].value_counts(dropna=False)

data['AJCC Clinical N'].value_counts()

data.loc[data['AJCC Clinical N'] == '0', 'AJCC Clinical N'] = 'cN0'
data.loc[data['AJCC Clinical N'] == '1', 'AJCC Clinical N'] = 'cN1'
data.loc[data['AJCC Clinical N'] == 'C0', 'AJCC Clinical N'] = 'cN0'
data.loc[data['AJCC Clinical N'] == 'C1', 'AJCC Clinical N'] = 'cN1'
data.loc[data['AJCC Clinical N'] == 'C1A', 'AJCC Clinical N'] = 'cN1a'
data.loc[data['AJCC Clinical N'] == 'C1B', 'AJCC Clinical N'] = 'cN1b'
data.loc[data['AJCC Clinical N'] == 'C2', 'AJCC Clinical N'] = 'cN2'
data.loc[data['AJCC Clinical N'] == 'c0', 'AJCC Clinical N'] = 'cN0'
data.loc[data['AJCC Clinical N'] == 'c1', 'AJCC Clinical N'] = 'cN1'
data.loc[data['AJCC Clinical N'] == 'c1A', 'AJCC Clinical N'] = 'cN1a'
data.loc[data['AJCC Clinical N'] == 'c1B', 'AJCC Clinical N'] = 'cN1b'
data.loc[data['AJCC Clinical N'] == 'c1C', 'AJCC Clinical N'] = 'cN1c'
data.loc[data['AJCC Clinical N'] == 'c2', 'AJCC Clinical N'] = 'cN2'
data.loc[data['AJCC Clinical N'] == 'c2A', 'AJCC Clinical N'] = 'cN2a'
data.loc[data['AJCC Clinical N'] == 'c2B', 'AJCC Clinical N'] = 'cN2b'
data.loc[data['AJCC Clinical N'] == 'c3', 'AJCC Clinical N'] = 'cN3'
data.loc[data['AJCC Clinical N'] == 'cX', 'AJCC Clinical N'] = 'cNX'


data.loc[data['AJCC Clinical N'] == 'None assigned', 'AJCC Clinical N'] = np.NaN
data['AJCC Clinical N'].fillna('Unknown', inplace=True)
data.loc[data['AJCC Clinical N'] == "Unknown", 'AJCC Clinical N'] = np.NaN
data['AJCC Clinical N'].value_counts(dropna=False)

data['AJCC Clinical M'].value_counts()

data.loc[data['AJCC Clinical M'] == '0', 'AJCC Clinical M'] = 'cM0'
data.loc[data['AJCC Clinical M'] == '88', 'AJCC Clinical M'] = 'Not applicable (not defined)'
data.loc[data['AJCC Clinical M'] == 'C0', 'AJCC Clinical M'] = 'cM0'
data.loc[data['AJCC Clinical M'] == 'C1', 'AJCC Clinical M'] = 'cM1, pM1'
data.loc[data['AJCC Clinical M'] == 'c0', 'AJCC Clinical M'] = 'cM0'
data.loc[data['AJCC Clinical M'] == 'c1', 'AJCC Clinical M'] = 'cM1, pM1'
data.loc[data['AJCC Clinical M'] == 'c1A', 'AJCC Clinical M'] = 'cM1a, pM1a'
data.loc[data['AJCC Clinical M'] == 'c1B', 'AJCC Clinical M'] = 'cM1b, pM1b'
data.loc[data['AJCC Clinical M'] == 'cX', 'AJCC Clinical M'] = 'cMX'
data.loc[data['AJCC Clinical M'] == 'p1', 'AJCC Clinical M'] = 'cM1, pM1'
data.loc[data['AJCC Clinical M'] == 'p1A', 'AJCC Clinical M'] = 'cM1a, pM1a'
data.loc[data['AJCC Clinical M'] == 'p1B', 'AJCC Clinical M'] = 'cM1b, pM1b'


data.loc[data['AJCC Clinical M'] == 'None assigned', 'AJCC Clinical M'] = np.NaN
data['AJCC Clinical M'].fillna('Unknown', inplace=True)
data.loc[data['AJCC Clinical M'] == "Unknown", 'AJCC Clinical M'] = np.NaN
data['AJCC Clinical M'].value_counts(dropna=False)

data['AJCC Pathologic T'].value_counts()


data.loc[data['AJCC Pathologic T'] == '3', 'AJCC Pathologic T'] = 'pT3'
data.loc[data['AJCC Pathologic T'] == 'P0', 'AJCC Pathologic T'] = 'pT0'
data.loc[data['AJCC Pathologic T'] == 'P1', 'AJCC Pathologic T'] = 'pT1'
data.loc[data['AJCC Pathologic T'] == 'P2', 'AJCC Pathologic T'] = 'pT2'
data.loc[data['AJCC Pathologic T'] == 'P3', 'AJCC Pathologic T'] = 'pT3'
data.loc[data['AJCC Pathologic T'] == 'P4A', 'AJCC Pathologic T'] = 'pT4a'
data.loc[data['AJCC Pathologic T'] == 'p0', 'AJCC Pathologic T'] = 'pT0'
data.loc[data['AJCC Pathologic T'] == 'p1', 'AJCC Pathologic T'] = 'pT1'
data.loc[data['AJCC Pathologic T'] == 'p2', 'AJCC Pathologic T'] = 'pT2'
data.loc[data['AJCC Pathologic T'] == 'p3', 'AJCC Pathologic T'] = 'pT3'
data.loc[data['AJCC Pathologic T'] == 'p3A', 'AJCC Pathologic T'] = 'pT3a'
data.loc[data['AJCC Pathologic T'] == 'p3B', 'AJCC Pathologic T'] = 'pT3b'
data.loc[data['AJCC Pathologic T'] == 'p3C', 'AJCC Pathologic T'] = 'pT3c'
data.loc[data['AJCC Pathologic T'] == 'p4', 'AJCC Pathologic T'] = 'pT4'
data.loc[data['AJCC Pathologic T'] == 'p4A', 'AJCC Pathologic T'] = 'pT4a'
data.loc[data['AJCC Pathologic T'] == 'p4B', 'AJCC Pathologic T'] = 'pT4b'
data.loc[data['AJCC Pathologic T'] == 'pIS', 'AJCC Pathologic T'] = 'pTis'
data.loc[data['AJCC Pathologic T'] == 'pX', 'AJCC Pathologic T'] = 'pTX'

data.loc[data['AJCC Pathologic T'] == 'None assigned', 'AJCC Pathologic T'] = np.NaN
data['AJCC Pathologic T'].fillna('Unknown', inplace=True)
data.loc[data['AJCC Pathologic T'] == "Unknown", 'AJCC Pathologic T'] = np.NaN
data['AJCC Pathologic T'].value_counts(dropna=False)

staging = ['AJCC Clinical N', 'AJCC Clinical M', 'AJCC Pathologic T']
data.drop(staging, axis=1, inplace=True)

In [220]:
data.loc[data['Lymph Vascular Invasion'] == '0.0', 'Lymph Vascular Invasion'] = 'No'
data.loc[data['Lymph Vascular Invasion'] == '1.0', 'Lymph Vascular Invasion'] = 'Yes'
data.loc[data['Lymph Vascular Invasion'] == '8.0', 'Lymph Vascular Invasion'] = 'Unknown'
data.loc[data['Lymph Vascular Invasion'] == '9.0', 'Lymph Vascular Invasion'] = 'Unknown'
data.loc[data['Lymph Vascular Invasion'] == 'nan', 'Lymph Vascular Invasion'] = 'Unknown'


data.loc[data['Lymph Vascular Invasion'] == 'None assigned', 'Lymph Vascular Invasion'] = np.NaN
data['Lymph Vascular Invasion'].fillna('Unknown', inplace=True)
data.loc[data['Lymph Vascular Invasion'] == "Unknown", 'Lymph Vascular Invasion'] = np.NaN
data['Lymph Vascular Invasion'].value_counts(dropna=False)

No     33197
NaN    13965
Yes     6522
Name: Lymph Vascular Invasion, dtype: int64

In [221]:
lymph_cols = [col for col in data.columns if 'Lymph' in col]
lymph_cols

['Lymph Vascular Invasion']

In [222]:
data['CEA'].value_counts()
# Unknown site specific data definitions

20.0     16641
10.0     13242
998.0     3204
997.0      483
30.0       169
988.0       47
Name: CEA, dtype: int64

In [223]:
data.loc[data['CEA'] == '0.0', 'CEA'] = 'Unknown'
data.loc[data['CEA'] == '10.0', 'CEA'] = 'Elevated'
data.loc[data['CEA'] == '20.0', 'CEA'] = 'Normal'
data.loc[data['CEA'] == '30.0', 'CEA'] = 'Borderline'
data.loc[data['CEA'] == 'nan', 'CEA'] = 'Unknown'
data.loc[data['CEA'] == '988.0', 'CEA'] = 'Unknown'
data.loc[data['CEA'] == '997.0', 'CEA'] = 'Unknown'
data.loc[data['CEA'] == '998.0', 'CEA'] = 'Unknown'

In [224]:
data['CEA'].fillna('Unknown', inplace=True)
data.loc[data['CEA'] == "Unknown", 'CEA'] = np.NaN
data['CEA'].value_counts(dropna=False)

NaN           23632
Normal        16641
Elevated      13242
Borderline      169
Name: CEA, dtype: int64

data['Clinical Assessment of Regional Lymph Nodes'].value_counts(dropna=False)

data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '0.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'Unknown'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '10.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N1'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '20.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N1'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '30.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N1'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '100.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N1'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '110.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N2'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '120.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N2'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '200.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N2'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '400.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'N+'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == 'nan', 'Clinical Assessment of Regional Lymph Nodes'] = 'Unknown'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '888.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'Unknown'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '988.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'Unknown'
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == '999.0', 'Clinical Assessment of Regional Lymph Nodes'] = 'Unknown'
data['Clinical Assessment of Regional Lymph Nodes'].fillna('Unknown', inplace=True)
data.loc[data['Clinical Assessment of Regional Lymph Nodes'] == "Unknown", 'Clinical Assessment of Regional Lymph Nodes'] = np.NaN
data['Clinical Assessment of Regional Lymph Nodes'].value_counts(dropna=False)

In [225]:
data.loc[data['CEA value'] > 987, 'CEA value'] = np.NaN
data['CEA value'].describe()

count    38619.000000
mean        41.535524
std         46.561604
min          0.000000
25%          8.000000
50%         22.000000
75%         55.000000
max        150.000000
Name: CEA value, dtype: float64

In [226]:
data['CEA value'].isnull().sum() / data.shape[0]

0.28062364950450785

In [227]:
#if data['CEA value'] is null, fill with 'CEA Pretreatment Lab Value SSDI Item 3820',
data.loc[data['CEA value'].isnull(), 'CEA value'] = data.loc[data['CEA value'].isnull(), 'CEA Pretreatment Lab Value SSDI Item 3820']
print(data['CEA value'].describe())
data['CEA value'].isnull().sum() / data.shape[0]

count    38639.000000
mean        44.253552
std        159.465751
min          0.000000
25%          8.000000
50%         22.000000
75%         55.000000
max      10000.000000
Name: CEA value, dtype: float64


0.28025109902391776

In [228]:
data.drop(['CEA Pretreatment Lab Value SSDI Item 3820'], axis=1, inplace=True)

In [229]:
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '0.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'CEA negative'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '1.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'CEA positive'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '2.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'CEA borderline'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '3.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'Unknown'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '7.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'Unknown'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == '9.0', 'CEA Pretreatment Interpretation SSDI Item 3819'] = 'Unknown'


data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == 'nan', 'CEA Pretreatment Interpretation SSDI Item 3819'] = np.NaN
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == 'None assigned', 'CEA Pretreatment Interpretation SSDI Item 3819'] = np.NaN
data['CEA Pretreatment Interpretation SSDI Item 3819'].fillna('Unknown', inplace=True)
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == "Unknown", 'CEA Pretreatment Interpretation SSDI Item 3819'] = np.NaN
data['CEA Pretreatment Interpretation SSDI Item 3819'].value_counts(dropna=False)

NaN               44371
CEA negative       4969
CEA positive       4302
CEA borderline       42
Name: CEA Pretreatment Interpretation SSDI Item 3819, dtype: int64

In [230]:
data['CEA'].value_counts(dropna=False)

NaN           23632
Normal        16641
Elevated      13242
Borderline      169
Name: CEA, dtype: int64

In [231]:
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == 'CEA negative', 'CEA'] = 'Normal'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == 'CEA positive', 'CEA'] = 'Elevated'
data.loc[data['CEA Pretreatment Interpretation SSDI Item 3819'] == 'CEA borderline', 'CEA'] = 'Borderline'
data.loc[data['CEA'] == 'Unknown', 'CEA'] = np.NaN

In [232]:
data['CEA'].value_counts(dropna=False)

Normal        21610
Elevated      17544
NaN           14319
Borderline      211
Name: CEA, dtype: int64

In [233]:
data.drop(['CEA Pretreatment Interpretation SSDI Item 3819'], axis=1, inplace=True)

In [234]:
data['KRAS SSDI Item 3866'].value_counts()


9.0    10484
0.0      720
4.0      227
1.0      197
3.0       33
7.0       32
2.0       11
Name: KRAS SSDI Item 3866, dtype: int64

In [235]:
data.loc[data['KRAS SSDI Item 3866'] == '0.0', 'KRAS SSDI Item 3866'] = 'Normal, KRAS wild type'
data.loc[data['KRAS SSDI Item 3866'] == '1.0', 'KRAS SSDI Item 3866'] = 'Abnormal (mutated) in codon(s) 12, 13 and/or 61'
data.loc[data['KRAS SSDI Item 3866'] == '2.0', 'KRAS SSDI Item 3866'] = 'Abnormal (mutated) in codon 146 only'
data.loc[data['KRAS SSDI Item 3866'] == '3.0', 'KRAS SSDI Item 3866'] = 'Abnormal (mutated), but not in codon(s) 12, 13, 61, or 146'
data.loc[data['KRAS SSDI Item 3866'] == '4.0', 'KRAS SSDI Item 3866'] = 'Abnormal (mutated), NOS, codon(s) not specified'
data.loc[data['KRAS SSDI Item 3866'] == '7.0', 'KRAS SSDI Item 3866'] = 'Test ordered, results not in chart'
data.loc[data['KRAS SSDI Item 3866'] == '9.0', 'KRAS SSDI Item 3866'] = 'Not documented in medical record, KRAS not assessed or unknown if assessed'


data.loc[data['KRAS SSDI Item 3866'] == 'None assigned', 'KRAS SSDI Item 3866'] = np.NaN
data['KRAS SSDI Item 3866'].fillna('Unknown', inplace=True)
data.loc[data['KRAS SSDI Item 3866'] == "Unknown", 'KRAS SSDI Item 3866'] = np.NaN
data['KRAS SSDI Item 3866'].value_counts(dropna=False)

NaN                                                                           41980
Not documented in medical record, KRAS not assessed or unknown if assessed    10484
Normal, KRAS wild type                                                          720
Abnormal (mutated), NOS, codon(s) not specified                                 227
Abnormal (mutated) in codon(s) 12, 13 and/or 61                                 197
Abnormal (mutated), but not in codon(s) 12, 13, 61, or 146                       33
Test ordered, results not in chart                                               32
Abnormal (mutated) in codon 146 only                                             11
Name: KRAS SSDI Item 3866, dtype: int64

In [236]:
data['KRAS'].value_counts()

998.0    22555
20.0      1730
10.0      1053
997.0      182
988.0       47
Name: KRAS, dtype: int64

In [237]:
data.loc[data['KRAS'] == '10.0', 'KRAS'] = 'Mutated'
data.loc[data['KRAS'] == '20.0', 'KRAS'] = 'Not mutated'
data.loc[data['KRAS'] == 'nan', 'KRAS'] = 'Unknown'
data.loc[data['KRAS'] == '988.0', 'KRAS'] = 'Unknown'
data.loc[data['KRAS'] == '997.0', 'KRAS'] = 'Unknown'
data.loc[data['KRAS'] == '998.0', 'KRAS'] = 'Unknown'
data.fillna('Unknown', inplace=True)
data.loc[data['KRAS'] == "Unknown", 'KRAS'] = np.NaN
data['KRAS'].value_counts(dropna=False)

NaN            50901
Not mutated     1730
Mutated         1053
Name: KRAS, dtype: int64

In [238]:
data.loc[data['KRAS SSDI Item 3866'] == 'Normal, KRAS wild type', 'KRAS'] = 'Not mutated'
data.loc[data['KRAS SSDI Item 3866'] == 'Abnormal (mutated) in codon(s) 12, 13 and/or 61', 'KRAS'] = 'Mutated'
data.loc[data['KRAS SSDI Item 3866'] == 'Abnormal (mutated) in codon 146 only', 'KRAS'] = 'Mutated'
data.loc[data['KRAS SSDI Item 3866'] == 'Abnormal (mutated), but not in codon(s) 12, 13, 61, or 146', 'KRAS'] = 'Mutated'
data.loc[data['KRAS SSDI Item 3866'] == 'Abnormal (mutated), NOS, codon(s) not specified', 'KRAS'] = 'Mutated'
data.loc[data['KRAS'] == 'Unknown', 'KRAS'] = np.NaN
data['KRAS'].value_counts(dropna=False)

NaN            49713
Not mutated     2450
Mutated         1521
Name: KRAS, dtype: int64

In [239]:
data.drop(['KRAS SSDI Item 3866'], axis=1, inplace=True)

In [240]:
data['Microsatellite Instability'].value_counts(dropna=False)

Unknown    23471
998.0      14171
20.0        9504
988.0       4876
60.0         624
40.0         455
997.0        349
50.0         234
Name: Microsatellite Instability, dtype: int64

In [241]:
data.loc[data['Microsatellite Instability'] == '20.0', 'Microsatellite Instability'] = 'MSI stable'
data.loc[data['Microsatellite Instability'] == '40.0', 'Microsatellite Instability'] = 'MSI stable'
data.loc[data['Microsatellite Instability'] == '50.0', 'Microsatellite Instability'] = 'MSI high'
data.loc[data['Microsatellite Instability'] == '60.0', 'Microsatellite Instability'] = 'MSI high'
data.loc[data['Microsatellite Instability'] == '988.0', 'Microsatellite Instability'] = 'Unknown'
data.loc[data['Microsatellite Instability'] == '997.0', 'Microsatellite Instability'] = 'Unknown'
data.loc[data['Microsatellite Instability'] == '998.0', 'Microsatellite Instability'] = 'Unknown'
data.loc[data['Microsatellite Instability'] == '999.0', 'Microsatellite Instability'] = 'Unknown'
data.loc[data['Microsatellite Instability'] == 'nan', 'Microsatellite Instability'] = 'Unknown'
data.fillna('Unknown', inplace=True)
data.loc[data['Microsatellite Instability'] == "Unknown", 'Microsatellite Instability'] = np.NaN
data['Microsatellite Instability'].value_counts(dropna=False)


NaN           42867
MSI stable     9959
MSI high        858
Name: Microsatellite Instability, dtype: int64

In [242]:
data['Microsatellite Instability (MSI) SSDI Item 3890'].value_counts()

Unknown    41980
0.0         6581
9.0         4640
2.0          303
1.0          180
Name: Microsatellite Instability (MSI) SSDI Item 3890, dtype: int64

In [243]:
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == '0.0', 'Microsatellite Instability (MSI) SSDI Item 3890'] = 'MSI stable'
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == '1.0', 'Microsatellite Instability (MSI) SSDI Item 3890'] = 'MSI stable'
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == '2.0', 'Microsatellite Instability (MSI) SSDI Item 3890'] = 'MSI high'
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == '9.0', 'Microsatellite Instability (MSI) SSDI Item 3890'] = 'Unknown'
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == 'nan', 'Microsatellite Instability (MSI) SSDI Item 3890'] = 'Unknown'
data.fillna('Unknown', inplace=True)
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == "Unknown", 'Microsatellite Instability (MSI) SSDI Item 3890'] = np.NaN
data['Microsatellite Instability (MSI) SSDI Item 3890'].value_counts(dropna=False)

NaN           46620
MSI stable     6761
MSI high        303
Name: Microsatellite Instability (MSI) SSDI Item 3890, dtype: int64

In [244]:
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == 'MSI stable', 'Microsatellite Instability'] = 'MSI stable'
data.loc[data['Microsatellite Instability (MSI) SSDI Item 3890'] == 'MSI high', 'Microsatellite Instability'] = 'MSI high'
data.loc[data['Microsatellite Instability'] == "Unknown", 'Microsatellite Instability'] = np.NaN
data['Microsatellite Instability'].value_counts(dropna=False)

NaN           35803
MSI stable    16720
MSI high       1161
Name: Microsatellite Instability, dtype: int64

In [245]:
data.drop('Microsatellite Instability (MSI) SSDI Item 3890', axis=1, inplace=True)

In [246]:
data['Perineural invasion'].value_counts(dropna=False)

0.0        31279
Unknown    18071
10.0        4287
988.0         47
Name: Perineural invasion, dtype: int64

In [247]:
data.loc[data['Perineural invasion'] == '0.0', 'Perineural invasion'] = 'No'
data.loc[data['Perineural invasion'] == '10.0', 'Perineural invasion'] = 'Yes'
data.loc[data['Perineural invasion'] == 'nan', 'Perineural invasion'] = 'Unknown'
data.loc[data['Perineural invasion'] == '988.0', 'Perineural invasion'] = 'Unknown'
data.loc[data['Perineural invasion'] == '998.0', 'Perineural invasion'] = 'Unknown'

data.fillna('Unknown', inplace=True)
data.loc[data['Perineural invasion'] == "Unknown", 'Perineural invasion'] = np.NaN
data['Perineural invasion'].value_counts(dropna=False)

No     31279
NaN    18118
Yes     4287
Name: Perineural invasion, dtype: int64

In [248]:
data['Perineural Invasion SSDI Item 3909'].value_counts()

Unknown    41980
0.0         8325
9.0         1861
1.0         1518
Name: Perineural Invasion SSDI Item 3909, dtype: int64

In [249]:
data.loc[data['Perineural Invasion SSDI Item 3909'] == '0.0', 'Perineural invasion'] = 'No'
data.loc[data['Perineural Invasion SSDI Item 3909'] == '1.0', 'Perineural invasion'] = 'Yes'

data['Perineural invasion'].value_counts(dropna=False)


No     39604
NaN     8275
Yes     5805
Name: Perineural invasion, dtype: int64

In [250]:
data.drop('Perineural Invasion SSDI Item 3909', axis=1, inplace=True)

data['18q Loss of Heterozygosity (LOH)'].value_counts(dropna=False)

data.loc[data['18q Loss of Heterozygosity (LOH)'] == '10.0', '18q Loss of Heterozygosity (LOH)'] = 'Yes'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '20.0', '18q Loss of Heterozygosity (LOH)'] = 'No'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '30.0', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == 'nan', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '988.0', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '997.0', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '998.0', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.loc[data['18q Loss of Heterozygosity (LOH)'] == '999.0', '18q Loss of Heterozygosity (LOH)'] = 'Unknown'
data.fillna('Unknown', inplace=True)
data.loc[data['18q Loss of Heterozygosity (LOH)'] == "Unknown", '18q Loss of Heterozygosity (LOH)'] = np.NaN
data['18q Loss of Heterozygosity (LOH)'].value_counts(dropna=False)

Clinical Assessment of Regional Lymph Nodes ??????

data.drop(['18q Loss of Heterozygosity (LOH)'], axis=1, inplace=True)

In [251]:
data['Surgical Procedure of Primary Site at any CoC Facility'].value_counts(dropna=False)
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '30.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'LAR'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '40.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'LAR'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '50.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'APR'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '60.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'Proctocolectomy'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '70.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'Pelvic exenteration'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '80.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'LAR'
data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '90.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'Unknown'
data['Surgical Procedure of Primary Site at any CoC Facility'].value_counts(dropna=False)

LAR                    37665
APR                    13035
Pelvic exenteration     1754
Proctocolectomy         1230
Name: Surgical Procedure of Primary Site at any CoC Facility, dtype: int64

In [252]:
#if data['Surgical Procedure of Primary Site at any CoC Facility'] is numeric, then change it to 'non-op'
try:
    data.loc[data['Surgical Procedure of Primary Site at any CoC Facility'] == '0.0', 'Surgical Procedure of Primary Site at any CoC Facility'] = 'No surgery'
except ValueError:
    pass

In [253]:
def check_numeric(x):
    try:
        float(x)
        return True
    except:
        return False

In [254]:
data.reset_index(inplace=True)

In [255]:
for x in range(len(data)):
    if check_numeric(data['Surgical Procedure of Primary Site at any CoC Facility'][x]) == True:
        data['Surgical Procedure of Primary Site at any CoC Facility'][x] = 'Local excision'
data['Surgical Procedure of Primary Site at any CoC Facility'].value_counts(dropna=False)

LAR                    37665
APR                    13035
Pelvic exenteration     1754
Proctocolectomy         1230
Name: Surgical Procedure of Primary Site at any CoC Facility, dtype: int64

In [256]:
# data['Location of Radiation Therapy'].value_counts()


In [257]:
# data.loc[data['Location of Radiation Therapy'] == '0.0', 'Location of Radiation Therapy'] = 'No radiation treatment'
# data.loc[data['Location of Radiation Therapy'] == '1.0', 'Location of Radiation Therapy'] = 'This facility'
# data.loc[data['Location of Radiation Therapy'] == '2.0', 'Location of Radiation Therapy'] = 'This facility'
# data.loc[data['Location of Radiation Therapy'] == '3.0', 'Location of Radiation Therapy'] = 'Elsewhere'
# data.loc[data['Location of Radiation Therapy'] == '4.0', 'Location of Radiation Therapy'] = 'Elsewhere'
# data.loc[data['Location of Radiation Therapy'] == '8.0', 'Location of Radiation Therapy'] = 'Other'
# data.loc[data['Location of Radiation Therapy'] == '9.0', 'Location of Radiation Therapy'] = 'Unknown'

# data.loc[data['Location of Radiation Therapy'] == 'None assigned', 'Location of Radiation Therapy'] = np.NaN
# data['Location of Radiation Therapy'].fillna('Unknown', inplace=True)
# data.loc[data['Location of Radiation Therapy'] == "Unknown", 'Location of Radiation Therapy'] = np.NaN
# data = data.loc[data['Location of Radiation Therapy'] != 'No radiation treatment']
# data['Location of Radiation Therapy'].value_counts(dropna=False)

In [258]:
# data['Phase I Radiation Treatment Modality'].value_counts()

In [259]:
# data['Brachytherapy'] = 0
# data.loc[data['Phase I Radiation Treatment Modality'] == '7.0', 'Brachytherapy'] = 1
# data.loc[data['Phase I Radiation Treatment Modality'] == '8.0', 'Brachytherapy'] = 1
# data.loc[data['Phase I Radiation Treatment Modality'] == '9.0', 'Brachytherapy'] = 1
# data.loc[data['Phase I Radiation Treatment Modality'] == '10.0', 'Brachytherapy'] = 1
# data.loc[data['Phase I Radiation Treatment Modality'] == '11.0', 'Brachytherapy'] = 1
# data.loc[data['Phase I Radiation Treatment Modality'] == '12.0', 'Brachytherapy'] = 1
# data['Brachytherapy'].value_counts()

In [260]:
# brachy_pcr = pcr_by_col(data, 'Brachytherapy')
# brachy_pcr.to_csv('../results_p/brachy_pcr.csv')

In [261]:
# data['Proton'] = 0
# data.loc[data['Phase I Radiation Treatment Modality'] == '3.0', 'Proton'] = 1
# data['Proton'].value_counts()

In [262]:
# proton_pcr = pcr_by_col(data, 'Proton')
# proton_pcr.to_csv('../results_p/proton_pcr.csv')

In [263]:
# data.drop(['Proton', 'Brachytherapy'], axis=1, inplace=True)

In [264]:
# data.loc[data['Location of Radiation Therapy'] == '0.0', 'Location of Radiation Therapy'] = 'No radiation treatment'
# data.loc[data['Location of Radiation Therapy'] == '1.0', 'Location of Radiation Therapy'] = 'This facility'
# data.loc[data['Location of Radiation Therapy'] == '2.0', 'Location of Radiation Therapy'] = 'This facility'
# data.loc[data['Location of Radiation Therapy'] == '3.0', 'Location of Radiation Therapy'] = 'Elsewhere'
# data.loc[data['Location of Radiation Therapy'] == '4.0', 'Location of Radiation Therapy'] = 'Elsewhere'
# data.loc[data['Location of Radiation Therapy'] == '8.0', 'Location of Radiation Therapy'] = 'Other'
# data.loc[data['Location of Radiation Therapy'] == '9.0', 'Location of Radiation Therapy'] = 'Unknown'

# data.loc[data['Location of Radiation Therapy'] == 'None assigned', 'Location of Radiation Therapy'] = np.NaN
# data['Location of Radiation Therapy'].fillna('Unknown', inplace=True)
# data.loc[data['Location of Radiation Therapy'] == "Unknown", 'Location of Radiation Therapy'] = np.NaN
# data = data.loc[data['Location of Radiation Therapy'] != 'No radiation treatment']
# data['Location of Radiation Therapy'].value_counts(dropna=False)

In [265]:
# data['Chemotherapy at any CoC Facility'].value_counts()


In [266]:
# data.loc[data['Chemotherapy at any CoC Facility'] == '0.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == '1.0', 'Chemotherapy at any CoC Facility'] = 'Chemotherapy, single-agent'
# data.loc[data['Chemotherapy at any CoC Facility'] == '2.0', 'Chemotherapy at any CoC Facility'] = 'Chemotherapy, single-agent'
# data.loc[data['Chemotherapy at any CoC Facility'] == '3.0', 'Chemotherapy at any CoC Facility'] = 'Chemotherapy, multi-agent'
# data.loc[data['Chemotherapy at any CoC Facility'] == '82.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == '85.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == '86.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == '87.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == '88.0', 'Chemotherapy at any CoC Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at any CoC Facility'] == 'None assigned', 'Chemotherapy at any CoC Facility'] = np.NaN
# data['Chemotherapy at any CoC Facility'].fillna('Unknown', inplace=True)
# data.loc[data['Chemotherapy at any CoC Facility'] == "Unknown", 'Chemotherapy at any CoC Facility'] = np.NaN

# data['Chemotherapy at any CoC Facility'].value_counts(dropna=False)

In [267]:
# data['Immunotherapy at any CoC Facility'].value_counts()


In [268]:
# data.loc[data['Immunotherapy at any CoC Facility'] == '0.0', 'Immunotherapy at any CoC Facility'] = 'No'
# data.loc[data['Immunotherapy at any CoC Facility'] == '1.0', 'Immunotherapy at any CoC Facility'] = 'Yes'
# data.loc[data['Immunotherapy at any CoC Facility'] == '82.0', 'Immunotherapy at any CoC Facility'] = 'No'
# data.loc[data['Immunotherapy at any CoC Facility'] == '86.0', 'Immunotherapy at any CoC Facility'] = 'No'
# data.loc[data['Immunotherapy at any CoC Facility'] == '87.0', 'Immunotherapy at any CoC Facility'] = 'No'
# data.loc[data['Immunotherapy at any CoC Facility'] == '88.0', 'Immunotherapy at any CoC Facility'] = 'No'


# data.loc[data['Immunotherapy at any CoC Facility'] == 'None assigned', 'Immunotherapy at any CoC Facility'] = np.NaN
# data['Immunotherapy at any CoC Facility'].fillna('Unknown', inplace=True)
# data.loc[data['Immunotherapy at any CoC Facility'] == "Unknown", 'Immunotherapy at any CoC Facility'] = np.NaN
# data['Immunotherapy at any CoC Facility'].value_counts(dropna=False)

In [269]:
# data['Systemic/Surgery Sequence'].value_counts()


In [270]:
# data.loc[data['Systemic/Surgery Sequence'] == '0.0', 'Systemic/Surgery Sequence'] = 'Not neo-adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '2.0', 'Systemic/Surgery Sequence'] = 'Neo-adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '3.0', 'Systemic/Surgery Sequence'] = 'Not neo-adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '4.0', 'Systemic/Surgery Sequence'] = 'Neo-adjuvant and adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '5.0', 'Systemic/Surgery Sequence'] = 'Not neo-adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '6.0', 'Systemic/Surgery Sequence'] = 'Not neo-adjuvant'
# data.loc[data['Systemic/Surgery Sequence'] == '9.0', 'Systemic/Surgery Sequence'] = 'Not neo-adjuvant'

# data.loc[data['Systemic/Surgery Sequence'] == 'None assigned', 'Systemic/Surgery Sequence'] = np.NaN
# data.loc[data['Systemic/Surgery Sequence'] == "Unknown", 'Systemic/Surgery Sequence'] = np.NaN
# data.loc[data['Systemic/Surgery Sequence'] == 'nan', 'Systemic/Surgery Sequence'] = np.NaN
# data['Systemic/Surgery Sequence'].fillna('Unknown', inplace=True)
# data.loc[data['Systemic/Surgery Sequence'] == "Unknown", 'Systemic/Surgery Sequence'] = np.NaN
# data['Systemic/Surgery Sequence'].value_counts(dropna=False)

In [271]:
# data['ict'].value_counts()

In [272]:
# pcr_by_col(data, 'ict')

In [273]:
# pcr_by_col(data, 'cct')

In [274]:
# data['Chemotherapy at this Facility'].value_counts()


In [275]:
# data.loc[data['Chemotherapy at this Facility'] == '0.0', 'Chemotherapy at this Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at this Facility'] == '1.0', 'Chemotherapy at this Facility'] = 'Unknown'
# data.loc[data['Chemotherapy at this Facility'] == '2.0', 'Chemotherapy at this Facility'] = 'Single-agent'
# data.loc[data['Chemotherapy at this Facility'] == '3.0', 'Chemotherapy at this Facility'] = 'Multiagent'
# data.loc[data['Chemotherapy at this Facility'] == '82.0', 'Chemotherapy at this Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at this Facility'] == '85.0', 'Chemotherapy at this Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at this Facility'] == '86.0', 'Chemotherapy at this Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at this Facility'] == '87.0', 'Chemotherapy at this Facility'] = 'No chemotherapy'
# data.loc[data['Chemotherapy at this Facility'] == '88.0', 'Chemotherapy at this Facility'] = 'Unknown'

# data.loc[data['Chemotherapy at this Facility'] == 'nan', 'Chemotherapy at this Facility'] = np.NaN
# data.loc[data['Chemotherapy at this Facility'] == 'None assigned', 'Chemotherapy at this Facility'] = np.NaN
# data['Chemotherapy at this Facility'].fillna('Unknown', inplace=True)
# data.loc[data['Chemotherapy at this Facility'] == "Unknown", 'Chemotherapy at this Facility'] = np.NaN
# data['Chemotherapy at this Facility'].value_counts(dropna=False)

In [276]:
# chemo_pcr = pcr_by_col(data, 'Chemotherapy at this Facility')
# chemo_pcr.head()

In [277]:
# chemo_pcr.to_csv('../results_p/chemo_pcr.csv')

In [278]:
# data['Immunotherapy at this Facility'].value_counts()

In [279]:
# data.loc[data['Immunotherapy at this Facility'] == '0.0', 'Immunotherapy at this Facility'] = 0
# data.loc[data['Immunotherapy at this Facility'] == '1.0', 'Immunotherapy at this Facility'] = 1
# data.loc[data['Immunotherapy at this Facility'] == '82.0', 'Immunotherapy at this Facility'] = 0
# data.loc[data['Immunotherapy at this Facility'] == '86.0', 'Immunotherapy at this Facility'] = 0
# data.loc[data['Immunotherapy at this Facility'] == '87.0', 'Immunotherapy at this Facility'] = 0
# data.loc[data['Immunotherapy at this Facility'] == '88.0', 'Immunotherapy at this Facility'] = 0

# data.loc[data['Immunotherapy at this Facility'] == 'nan', 'Immunotherapy at this Facility'] = np.NaN
# data.loc[data['Immunotherapy at this Facility'] == 'None assigned', 'Immunotherapy at this Facility'] = np.NaN
# data['Immunotherapy at this Facility'].fillna('Unknown', inplace=True)
# data.loc[data['Immunotherapy at this Facility'] == "Unknown", 'Immunotherapy at this Facility'] = np.NaN
# data['Immunotherapy at this Facility'].value_counts(dropna=False)

In [280]:
data['Palliative Care at this Facility'].value_counts()

0.0    53684
Name: Palliative Care at this Facility, dtype: int64

In [281]:
data.loc[data['Palliative Care at this Facility'] == '0', 'Palliative Care at this Facility'] = 'No palliative care provided'
data.loc[data['Palliative Care at this Facility'] == '1', 'Palliative Care at this Facility'] = 'Surgery (which may involve a bypass procedure) to alleviate symptoms, but no attempt to diagnose, stage, or treat the primary tumor is made'
data.loc[data['Palliative Care at this Facility'] == '2', 'Palliative Care at this Facility'] = 'Radiation therapy to alleviate symptoms, but no attempt to diagnose, stage, or treat the primary tumor is made'
data.loc[data['Palliative Care at this Facility'] == '3', 'Palliative Care at this Facility'] = 'Chemotherapy, hormone therapy, or othersystemic drugs to alleviate symptoms, but no attempt to diagnose, stage, or treat the primary tumor is made'
data.loc[data['Palliative Care at this Facility'] == '4', 'Palliative Care at this Facility'] = 'Patient received or was referred for pain management therapy with no other palliative care'
data.loc[data['Palliative Care at this Facility'] == '5', 'Palliative Care at this Facility'] = 'Any combination of codes 1, 2, and/or 3 without code 4'
data.loc[data['Palliative Care at this Facility'] == '6', 'Palliative Care at this Facility'] = 'Any combination of codes 1, 2, and/or 3 with code 4'
data.loc[data['Palliative Care at this Facility'] == '7', 'Palliative Care at this Facility'] = 'Palliative care was performed or referred, but no information on the type of procedure is available in the patient record. Palliative care was provided that does not fit the descriptions for codes 1-6'
data.loc[data['Palliative Care at this Facility'] == '9', 'Palliative Care at this Facility'] = 'It is unknown if palliative care was performed or referred; not stated in patient record'


data.loc[data['Palliative Care at this Facility'] == 'None assigned', 'Palliative Care at this Facility'] = np.NaN
data['Palliative Care at this Facility'].fillna('Unknown', inplace=True)
data.loc[data['Palliative Care at this Facility'] == "Unknown", 'Palliative Care at this Facility'] = np.NaN
data['Palliative Care at this Facility'].value_counts(dropna=False)

0.0    53684
Name: Palliative Care at this Facility, dtype: int64

In [282]:
data.drop(['Palliative Care at this Facility'], axis=1, inplace=True)

In [283]:
data['Metastatic Involvement Other'].value_counts()


Unknown    30344
0.0        23205
1.0           99
9.0           34
8.0            2
Name: Metastatic Involvement Other, dtype: int64

In [284]:
data.loc[data['Metastatic Involvement Other'] == '0.0', 'Metastatic Involvement Other'] = 0
data.loc[data['Metastatic Involvement Other'] == '1.0', 'Metastatic Involvement Other'] = 1
data.loc[data['Metastatic Involvement Other'] == '2.0', 'Metastatic Involvement Other'] = 1
data.loc[data['Metastatic Involvement Other'] == '9.0', 'Metastatic Involvement Other'] = np.NaN
data.loc[data['Metastatic Involvement Other'] == '8.0', 'Metastatic Involvement Other'] = np.NaN
data.loc[data['Metastatic Involvement Other'] == 'nan', 'Metastatic Involvement Other'] = np.NaN


data.loc[data['Metastatic Involvement Other'] == 'None assigned', 'Metastatic Involvement Other'] = np.NaN
data['Metastatic Involvement Other'].fillna('Unknown', inplace=True)
data.loc[data['Metastatic Involvement Other'] == "Unknown", 'Metastatic Involvement Other'] = np.NaN
data['Metastatic Involvement Other'].value_counts(dropna=False)

NaN    30380
0.0    23205
1.0       99
Name: Metastatic Involvement Other, dtype: int64

In [285]:
data.drop(['Metastatic Involvement Other'], axis=1, inplace=True)

In [286]:
met_cols = [col for col in data.columns if 'Met' in col]
met_cols

['Metastatic Liver Involvement', 'Metastatic Liver Involvement.1']

In [287]:
data['Metastatic Liver Involvement'].value_counts()


0.0        29877
Unknown    23340
1.0          412
9.0           55
Name: Metastatic Liver Involvement, dtype: int64

In [288]:
#if 'Metastatic Liver Involvement' is missing, fill with Metastatic Liver Involvement.1
data.loc[data['Metastatic Liver Involvement'] == 'Unknown', 'Metastatic Liver Involvement'] = data['Metastatic Liver Involvement.1']
data.loc[data['Metastatic Liver Involvement'].isnull(), 'Metastatic Liver Involvement'] = data['Metastatic Liver Involvement.1']
data['Metastatic Liver Involvement'].value_counts()


0.0    52745
1.0      857
9.0       81
8.0        1
Name: Metastatic Liver Involvement, dtype: int64

In [289]:
data.loc[data['Metastatic Liver Involvement'] == '0.0', 'Metastatic Liver Involvement'] = 0
data.loc[data['Metastatic Liver Involvement'] == '1.0', 'Metastatic Liver Involvement'] = 1
data.loc[data['Metastatic Liver Involvement'] == '8.0', 'Metastatic Liver Involvement'] = 'Unknown'
data.loc[data['Metastatic Liver Involvement'] == '9.0', 'Metastatic Liver Involvement'] = 'Unknown'
data.loc[data['Metastatic Liver Involvement'] == 'nan', 'Metastatic Liver Involvement'] = 'Unknown'


data.loc[data['Metastatic Liver Involvement'] == 'None assigned', 'Metastatic Liver Involvement'] = np.NaN
data['Metastatic Liver Involvement'].fillna('Unknown', inplace=True)
data.loc[data['Metastatic Liver Involvement'] == "Unknown", 'Metastatic Liver Involvement'] = np.NaN
data['Metastatic Liver Involvement'].value_counts(dropna=False)

0.0    52745
1.0      857
NaN       82
Name: Metastatic Liver Involvement, dtype: int64

In [290]:
data.drop(['Metastatic Liver Involvement.1'], axis=1, inplace=True)

In [291]:
data['Medicaid Expansion Status State Group'].value_counts()


0.0    19076
1.0    15699
2.0     8730
3.0     7492
9.0     2687
Name: Medicaid Expansion Status State Group, dtype: int64

In [292]:
data.loc[data['Medicaid Expansion Status State Group'] == '0.0', 'Medicaid Expansion Status State Group'] = 'Non-Expansion State'
data.loc[data['Medicaid Expansion Status State Group'] == '1.0', 'Medicaid Expansion Status State Group'] = 'Early Expansion (before 1/2014)'
data.loc[data['Medicaid Expansion Status State Group'] == '2.0', 'Medicaid Expansion Status State Group'] = 'Early Expansion (before 1/2014)'
data.loc[data['Medicaid Expansion Status State Group'] == '3.0', 'Medicaid Expansion Status State Group'] = 'Late Expansion States (after 1/2014)'
data.loc[data['Medicaid Expansion Status State Group'] == '9.0', 'Medicaid Expansion Status State Group'] = 'Suppressed for Ages 0-39'

data.loc[data['Medicaid Expansion Status State Group'] == 'nan', 'Medicaid Expansion Status State Group'] = np.NaN
data.loc[data['Medicaid Expansion Status State Group'] == 'None assigned', 'Medicaid Expansion Status State Group'] = np.NaN
data['Medicaid Expansion Status State Group'].fillna('Unknown', inplace=True)
data.loc[data['Medicaid Expansion Status State Group'] == "Unknown", 'Medicaid Expansion Status State Group'] = np.NaN
data['Medicaid Expansion Status State Group'].value_counts(dropna=False)

Early Expansion (before 1/2014)         24429
Non-Expansion State                     19076
Late Expansion States (after 1/2014)     7492
Suppressed for Ages 0-39                 2687
Name: Medicaid Expansion Status State Group, dtype: int64

In [293]:
# data['Number of Phases of Radiation Treatment to this Volume'].value_counts()


In [294]:
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == '0.0', 'Number of Phases of Radiation Treatment to this Volume'] = 'No radiation treatment'
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == '1.0', 'Number of Phases of Radiation Treatment to this Volume'] = '1 phase'
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == '2.0', 'Number of Phases of Radiation Treatment to this Volume'] = '2 phases'
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == '3.0', 'Number of Phases of Radiation Treatment to this Volume'] = '3 phases'
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == '4.0', 'Number of Phases of Radiation Treatment to this Volume'] = '4 or more phases'


# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == 'None assigned', 'Number of Phases of Radiation Treatment to this Volume'] = np.NaN
# data['Number of Phases of Radiation Treatment to this Volume'].fillna('Unknown', inplace=True)
# data.loc[data['Number of Phases of Radiation Treatment to this Volume'] == "Unknown", 'Number of Phases of Radiation Treatment to this Volume'] = np.NaN
# data['Number of Phases of Radiation Treatment to this Volume'].value_counts(dropna=False)

In [295]:
# print(data.shape)
# data = data[data['Number of Phases of Radiation Treatment to this Volume'] != 'No radiation treatment']
# print(data.shape)

In [296]:
# data.drop(['Number of Phases of Radiation Treatment to this Volume'], axis=1, inplace=True)

In [297]:
# data['Radiation Treatment Discontinued Early'].value_counts()


In [298]:
# data.loc[data['Radiation Treatment Discontinued Early'] == '0.0', 'Radiation Treatment Discontinued Early'] = 'No radiation treatment'
# data.loc[data['Radiation Treatment Discontinued Early'] == '1.0', 'Radiation Treatment Discontinued Early'] = 'Radiation treatment completed as prescribed'
# data.loc[data['Radiation Treatment Discontinued Early'] == '2.0', 'Radiation Treatment Discontinued Early'] = 'Radiation treatment discontinued early; toxicity'
# data.loc[data['Radiation Treatment Discontinued Early'] == '3.0', 'Radiation Treatment Discontinued Early'] = 'Radiation treatment discontinued early; contraindicated to other patient risk factors (comorbid conditions, advanced age, progression of tumor prior to planned radiation, etc.'
# data.loc[data['Radiation Treatment Discontinued Early'] == '4.0', 'Radiation Treatment Discontinued Early'] = 'Radiation treatment discontinued early; patient decision'


# data.loc[data['Radiation Treatment Discontinued Early'] == 'None assigned', 'Radiation Treatment Discontinued Early'] = np.NaN
# data['Radiation Treatment Discontinued Early'].fillna('Unknown', inplace=True)
# data.loc[data['Radiation Treatment Discontinued Early'] == "Unknown", 'Radiation Treatment Discontinued Early'] = np.NaN
# data['Radiation Treatment Discontinued Early'].value_counts(dropna=False)

In [299]:
# data.drop(['Radiation Treatment Discontinued Early'], axis=1, inplace=True)

In [300]:
data.head()

Case Key                      Facility Type  \
0  D0d14a662-dde0-4a0e-a6f0-a0e0db2d19e2          Academic/Research Program   
1  Dcd9758ae-2308-45cf-bbf1-b3ab4ed2e48f          Academic/Research Program   
2  D656e0503-a772-440d-a60a-c9d8bd9c520b          Academic/Research Program   
3  D67bf0834-7b7d-41c7-a320-ab0438fe764e          Academic/Research Program   
4  D1557dfde-4686-4534-8d7f-bf743fdc51bf  Integrated Network Cancer Program   

  Facility Location  Age at Diagnosis     Sex   Race Spanish Hispanic Origin  \
0                NE              78.0  Female  White                 Unknown   
1           Midwest              70.0    Male  White            Non-Hispanic   
2                NE              82.0    Male  White            Non-Hispanic   
3           Midwest              51.0    Male  White            Non-Hispanic   
4             South              84.0    Male  White            Non-Hispanic   

                       Primary Payor Urban/Rural 2013 Great Circle Distance  \
0                    Medicare/Public            Urban                   7.5   
1  Private Insurance or Managed Care            Urban                  26.5   
2                    Medicare/Public            Urban                   7.9   
3  Private Insurance or Managed Care            Urban               Unknown   
4                    Medicare/Public            Urban                   2.7   

  Charlson-Deyo Score Year of Diagnosis     Grade Size of Tumor  \
0          Score of 0            2010.0  Grade II          50.0   
1  Score of 2 or more            2012.0  Grade II          50.0   
2          Score of 0            2017.0   Unknown       Unknown   
3          Score of 0            2011.0  Grade II          15.0   
4          Score of 0            2015.0   Unknown          42.0   

  Metastatic Liver Involvement Lymph Vascular Invasion       CEA CEA value  \
0                            0                 Unknown  Elevated      32.0   
1                            0                      No    Normal       8.0   
2                            0                     Yes    Normal      34.0   
3                            0                      No   Unknown   Unknown   
4                            0                      No    Normal      22.0   

  Microsatellite Instability Perineural invasion     KRAS  \
0                    Unknown                 NaN  Unknown   
1                   MSI high                  No  Unknown   
2                 MSI stable                  No  Unknown   
3                 MSI stable                  No  Unknown   
4                    Unknown                  No  Mutated   

  Surgical Procedure of Primary Site at any CoC Facility  \
0                                                LAR       
1                                                LAR       
2                                                LAR       
3                                                LAR       
4                                                LAR       

  Radiation Surgery Sequence at any CoC Facility Reason For No Radiation  \
0                                            2.0                     0.0   
1                                            2.0                     0.0   
2                                            2.0                     0.0   
3                                            2.0                     0.0   
4                                            2.0                     0.0   

  Chemotherapy at any CoC Facility Last Contact or Death, Months from Dx  \
0                              2.0                                125.57   
1                              1.0                                 98.53   
2                              2.0                                  8.05   
3                              2.0                                 69.95   
4                              2.0                                 70.18   

  Tumor Size Summary 2016 Percent No High School Degree Quartiles 2012-2016  \
0       

data['AJCC 8th Edition Clinical M'].value_counts()


data.loc[data['AJCC 8th Edition Clinical M'] == 'CM1B', 'AJCC 8th Edition Clinical M'] = 'cM1b'
data.loc[data['AJCC 8th Edition Clinical M'] == 'c0', 'AJCC 8th Edition Clinical M'] = 'cM0'


data.loc[data['AJCC 8th Edition Clinical M'] == 'None assigned', 'AJCC 8th Edition Clinical M'] = np.NaN
data['AJCC 8th Edition Clinical M'].fillna('Unknown', inplace=True)
data.loc[data['AJCC 8th Edition Clinical M'] == "Unknown", 'AJCC 8th Edition Clinical M'] = np.NaN
data['AJCC 8th Edition Clinical M'].value_counts(dropna=False)

data['AJCC 8th Edition Clinical N'].value_counts()


data.loc[data['AJCC 8th Edition Clinical N'] == 'CN0', 'AJCC 8th Edition Clinical N'] = 'cN0'
data.loc[data['AJCC 8th Edition Clinical N'] == 'c0', 'AJCC 8th Edition Clinical N'] = 'cN0'


data.loc[data['AJCC 8th Edition Clinical N'] == 'None assigned', 'AJCC 8th Edition Clinical N'] = np.NaN
data['AJCC 8th Edition Clinical N'].fillna('Unknown', inplace=True)
data.loc[data['AJCC 8th Edition Clinical N'] == "Unknown", 'AJCC 8th Edition Clinical N'] = np.NaN
data['AJCC 8th Edition Clinical N'].value_counts(dropna=False)

data['AJCC 8th Edition Clinical T'].value_counts()


data.loc[data['AJCC 8th Edition Clinical T'] == 'CT1', 'AJCC 8th Edition Clinical T'] = 'cT1'
data.loc[data['AJCC 8th Edition Clinical T'] == 'c3', 'AJCC 8th Edition Clinical T'] = 'cT3'


data.loc[data['AJCC 8th Edition Clinical T'] == 'None assigned', 'AJCC 8th Edition Clinical T'] = np.NaN
data['AJCC 8th Edition Clinical T'].fillna('Unknown', inplace=True)
data.loc[data['AJCC 8th Edition Clinical T'] == "Unknown", 'AJCC 8th Edition Clinical T'] = np.NaN
data['AJCC 8th Edition Clinical T'].value_counts(dropna=False)

data.drop(['AJCC 8th Edition Clinical M', 'AJCC 8th Edition Clinical N', 'AJCC 8th Edition Clinical T'], axis=1, inplace=True)

<h1> Define outcomes for the surg group <h1>

In [301]:
#if Size of Tumor is missing, then fill it 'Tumor Size Summary 2016'
data.loc[data['Size of Tumor'] == 'Unknown', 'Size of Tumor'] = data['Tumor Size Summary 2016']

In [302]:
data.drop('Tumor Size Summary 2016', axis=1, inplace=True)

In [303]:
num_cols = ['Age at Diagnosis', 'Great Circle Distance', 'Size of Tumor']
# 'Surgical Dx and Staging Procedure, Days from Dx','CEA value', 'Treatment Started, Days from Dx', 'First Surgical Procedure, Days from Dx','Definitive Surgical Procedure, Days from Dx','Radiation, Days from Dx','Radiation Ended, Days from Start of Radiation','Systemic, Days from Dx','Chemotherapy, Days from Dx', 'Total Dose','days_chemo_rads'
for x in num_cols:
    data.loc[data[x] == 'Unknown', x] = np.NaN

In [304]:
for x in data.columns.to_list():
    data.loc[data[x] == 'Unknown', x] = np.NaN
    data.loc[data[x] == 'nan', x] = np.NaN

In [305]:
data['Year of Diagnosis'] = data['Year of Diagnosis'].astype(float)

In [306]:
data.rename({'CEA':'CEA Interpretation', 'Perineural invasion':'Perineural Invasion', 'Urban/Rural 2013':'Urban/Rural', 'Lymph Vascular Invasion':'Lymphovascular Invasion'}, axis=1, inplace=True)


In [307]:
data['pcr'].value_counts(normalize=True)


0.0    0.770844
1.0    0.229156
Name: pcr, dtype: float64

In [308]:
pcr_by_year = by_year(data, 'pcr')
pcr_by_year.head(10)


pcr                         0.0           1.0  total
Year of Diagnosis                                   
2010.0             3191 (74.0%)  1130 (26.0%)   4321
2011.0             3326 (74.0%)  1176 (26.0%)   4502
2012.0             3557 (74.0%)  1270 (26.0%)   4827
2013.0             3908 (75.0%)  1318 (25.0%)   5226
2014.0             4455 (77.0%)  1349 (23.0%)   5804
2015.0             4435 (78.0%)  1229 (22.0%)   5664
2016.0             4513 (78.0%)  1285 (22.0%)   5798
2017.0             4398 (79.0%)  1182 (21.0%)   5580
2018.0             4971 (81.0%)  1192 (19.0%)   6163
2019.0             4628 (80.0%)  1171 (20.0%)   5799

In [309]:
pcr_by_year.to_csv('../results/pcr_by_year.csv')

In [310]:
data.drop(['pstage', 'Last Contact or Death, Months from Dx'], axis=1, inplace=True)

In [311]:
cols = data.columns.to_list()
num_cols = ['Age at Diagnosis', 'Great Circle Distance', 'Size of Tumor', 'CEA value']
cat_cols = [x for x in cols if x not in num_cols]

In [312]:
cat_cols.remove('pcr')

In [313]:
#remove variables that have no variance across 'pcr'
for x in cat_cols:
    if data[x].value_counts(dropna=False).shape[0] == 1:
        print(x)
        data.drop(x, axis=1, inplace=True)
        cat_cols.remove(x)



Radiation Surgery Sequence at any CoC Facility


In [314]:
data.drop(columns=['Surgical Procedure of Primary Site at any CoC Facility'], inplace=True)

In [315]:
data.set_index('Case Key', inplace=True)
data.to_csv('../data/data_clean.csv', index_label='Case Key')

In [316]:
cols = data.columns.to_list()
num_cols = ['Age at Diagnosis', 'Great Circle Distance', 'Size of Tumor', 'CEA value']
cat_cols = [x for x in cols if x not in num_cols]

In [317]:
tableone = TableOne(data, categorical=cat_cols, groupby='pcr', pval=True)

/home/kchen/.local/lib/python3.8/site-packages/tableone/tableone.py:991: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df['percent'] = df['freq'].div(df.freq.sum(level=0),
/home/kchen/.local/lib/python3.8/site-packages/tableone/tableone.py:991: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df['percent'] = df['freq'].div(df.freq.sum(level=0),


In [ ]:
tableone.to_excel('../results/table1_raw2.xlsx')